// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorMt6D1IQPV68XWCaSPIbFR_JFez_v-E',
    appId: '1:605570058735:web:6e379d83f29c52410a8e1a',
    messagingSenderId: '605570058735',
    projectId: 'healthcar-app',
    authDomain: 'healthcar-app.firebaseapp.com',
    storageBucket: 'healthcar-app.firebasestorage.app',
    measurementId: 'G-4S99PJPVZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOHBvyBL8srMSCNpr5OZKlVCQZ1mYveFI',
    appId: '1:605570058735:android:8b8602928562c2210a8e1a',
    messagingSenderId: '605570058735',
    projectId: 'healthcar-app',
    storageBucket: 'healthcar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQJzY5ZfjhTIA41BhdbSL4UM9RvPBZu0',
    appId: '1:605570058735:ios:19a4586c056a54ce0a8e1a',
    messagingSenderId: '605570058735',
    projectId: 'healthcar-app',
    storageBucket: 'healthcar-app.firebasestorage.app',
    iosBundleId: 'com.example.healthcare',
  );
}
